---
  - hosts: all
    become: yes
    gather_facts: no

    tasks:
  
    - name: Import RPM Keys
      rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        #- https://artifacts.elastic.co/GPG-KEY-elasticsearch
        - https://download.docker.com/linux/centos/gpg

    - name: Add EPEL Repository
      yum:
        name: epel-release

        #- name: Add Elastic Repository
        #yum_repository:
        #name: elastic
        #description: Elasticsearch repository for 7.x packages
        #enabled: yes
        #gpgcheck: yes
        #baseurl: https://artifacts.elastic.co/packages/7.x/yum
        #gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        #file: elastic

    - name: Add Docker Repository
      yum_repository:
        name: docker-ce
        description: Docker repository for docker-ce
        enabled: yes
        module_hotfixes: true
        gpgcheck: yes
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Add Microsoft Repository
      yum_repository:
        name: packages-microsoft-com-prod
        description: Microsoft Repo for RHEL-based
        enabled: yes
        gpgcheck: yes
        baseurl: https://packages.microsoft.com/rhel/7/prod/
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        file: prod

    - name: Clean Yum Cache
      command: yum clean all

    - name: Install System Tools
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - nano
          - tmux
          - cockpit
          - git
          - wget
          - golang
          - bzip2
          - containerd.io
          - docker-ce 
          - docker-ce-cli
          - docker-compose-plugin

    - name: Start Firewalld Service
      systemd:
        name: firewalld
        state: started
        enabled: yes

###################################
# Firewall
###################################

    - name: Start Firewalld Service
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Add Elasticsearch Firewall Rule
      firewalld:
        zone: public
        port: 9200/tcp
        permanent: yes
        immediate: yes
        state: enabled
        
    - name: Add Kibana Firewall Rule
      firewalld:
        zone: public
        port: 5601/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Add Fleet Firewall Rule
      firewalld:
        zone: public
        port: 8220/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Add AtomicGUI Firewall Rule
      firewalld:
        zone: public
        port: 8487/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Add Caldera Firewall Rule
      firewalld:
        zone: public
        port: 8888/tcp
        permanent: yes
        immediate: yes
        state: enabled


###################################
# Powershell
###################################

    - name: Install Powershell
      yum:
        name: powershell
        state: present

    - name: Enable Powershell Remoting
      command: pwsh -Command {Enable-PSRemoting -Force}


###################################
# SSH Configuration
###################################

    - name: Uncomment Pass Auth Yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication\s+yes'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'

    - name: Comment out Passauth No
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication\s+no'
        line: '# PasswordAuthentication no'
        owner: root
        group: root
        mode: '0600'

    - name: Allow SSH Pubkey Auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication\s+yes'
        line: 'PubkeyAuthentication yes'
        owner: root
        group: root
        mode: '0600'

    - name: Add PS Subsystem to PS remote over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Subsystem powershell /usr/bin/pwsh -sshs -NoLogo'
        create: yes
        owner: root
        group: root
        mode: '0600'

    - name: Create Vagrant User SSH Directory
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        mode: '0700'

    - name: Retrieve Default Vagrant Pub Key
      command: wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys

    - name: Update Permissions of SSH Key
      file:
        path: /home/vagrant/.ssh/authorized_keys
        state: file
        owner: vagrant
        mode: '0600'
        
    - name: Add AuthorizedKeysFile to Config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysFile\s+\.ssh/authorized_keys'
        line: 'AuthorizedKeysFile %h/.ssh/authorized_keys'
        owner: root
        group: root
        mode: '0600'

    - name: Restart sshd service
      systemd:
        name: sshd
        state: restarted