---
  - hosts: all
    become: yes
    gather_facts: no

    tasks:
  
    - name: Import RPM Keys
      rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

    - name: Add EPEL Repository
      yum:
        name: epel-release

    - name: Add Docker-CE stable repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable Repo
        baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes

    - name: Add Microsoft Repository
      yum_repository:
        name: packages-microsoft-com-prod
        description: Microsoft Repo for RHEL-based
        enabled: yes
        gpgcheck: yes
        baseurl: https://packages.microsoft.com/rhel/7/prod/
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        file: prod

    - name: Clean Yum Cache
      command: yum clean all

    - name: Install System Tools
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - nano
          - tmux
          - ufw
          - cockpit
          - git
          - wget
          - jq
          - golang
          - bzip2
          - dos2unix
          - containerd.io
          - docker-ce 
          - docker-ce-cli
          - docker-compose-plugin


###################################
# Firewall
###################################

    - name: Start Firewalld Service
      systemd:
        name: ufw
        state: started
        enabled: yes

    - name: Add Elasticsearch Firewall Rule
      ufw:
        rule: allow
        port: 9200
        proto: tcp
        state: enabled
        
    - name: Add Kibana Firewall Rule
      ufw:
        rule: allow
        port: 5601
        proto: tcp
        state: enabled

    - name: Add Fleet Firewall Rule
      ufw:
        rule: allow
        port: 8220
        proto: tcp
        state: enabled

    - name: Add AtomicGUI Firewall Rule
      firewalld:
        zone: public
        port: 8487/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Add Caldera Firewall Rule
      firewalld:
        zone: public
        port: 8888/tcp
        permanent: yes
        immediate: yes
        state: enabled

###################################
# Elastic Container Project
###################################

    - name: Start and Enable Docker
      systemd: 
        name: docker
        state: started
        enabled: yes

    - name: Download ECP
      git:
        repo: https://github.com/peasead/elastic-container
        dest: /home/vagrant/elastic-container/

    - name: Add environment file
      copy:
        src: ./files/.env
        dest: /home/vagrant/elastic-container/.env

    - name: Confirm Directory Permissions
      file:
        path: /home/vagrant/elastic-container
        state: directory
        recurse: yes
        owner: vagrant
        group: vagrant
    
    - name: Run ECP Install
      command: /home/vagrant/elastic-container/elastic-container.sh stage
      args:
        chdir: /home/vagrant/elastic-container/

###################################
# Powershell
###################################

    - name: Install Powershell
      yum:
        name: powershell
        state: present

    - name: Enable Powershell Remoting
      command: pwsh -Command {Enable-PSRemoting -Force}


###################################
# SSH Configuration
###################################

    - name: Uncomment Pass Auth Yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication\s+yes'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'

    - name: Comment out Passauth No
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication\s+no'
        line: '# PasswordAuthentication no'
        owner: root
        group: root
        mode: '0600'

    - name: Allow SSH Pubkey Auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication\s+yes'
        line: 'PubkeyAuthentication yes'
        owner: root
        group: root
        mode: '0600'

    - name: Add PS Subsystem to PS remote over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Subsystem powershell /usr/bin/pwsh -sshs -NoLogo'
        create: yes
        owner: root
        group: root
        mode: '0600'

    - name: Create Vagrant User SSH Directory
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        mode: '0700'

    - name: Retrieve Default Vagrant Pub Key
      command: wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys

    - name: Update Permissions of SSH Key
      file:
        path: /home/vagrant/.ssh/authorized_keys
        state: file
        owner: vagrant
        mode: '0600'
        
    - name: Add AuthorizedKeysFile to Config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysFile\s+\.ssh/authorized_keys'
        line: 'AuthorizedKeysFile %h/.ssh/authorized_keys'
        owner: root
        group: root
        mode: '0600'

    - name: Restart sshd service
      systemd:
        name: sshd
        state: restarted