#$set_environment_variables = <<SCRIPT
#tee "/etc/profile.d/myvars.sh" > "/dev/null" <<EOF
# ECP file.
#export ECP_INFO=#{ENV['ECP_INFO']}
#EOF
#SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "ts.elastic", primary: true do |cfg|
    cfg.vm.box = "olympus/elastic"
    cfg.vm.box_version = "1.0.3"
    cfg.vm.hostname = "elastic"
    cfg.disksize.size = "256GB"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.56.10", auto_config: true
    cfg.vm.network "forwarded_port", guest: 5601, host: 5601
    cfg.vm.network "forwarded_port", guest: 9200, host: 9200
    cfg.vm.network "forwarded_port", guest: 8888, host: 8888

    cfg.vm.provider :virtualbox do |vb|
      vb.name = "ts.elastomic"
      vb.memory = 8192
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    # Enable PowerShell
    cfg.vm.provision "enable-psremoting", type: "shell", path: "../vagrant/scripts/enable-psremoting.sh"

    # Install Atomic Red Team
    cfg.vm.provision "install-atomic-redteam", type: "shell", path: "../vagrant/scripts/elastic/install-atomicredteam.ps1"

    # Caldera
    cfg.vm.provision "install-caldera", type: "shell", path: "../vagrant/scripts/install-caldera.sh"

    # Download and Start Container Project

    cfg.vm.provision "file", source: ".env", destination: "/home/vagrant/.env"

    cfg.vm.provision "download-and-install-ecp", type: "shell", path: "../vagrant/scripts/elastic/download-elastic-containers.sh"

    #cfg.vm.provision "download-install-ecp", type: "shell", path: "../vagrant/scripts/elastic/download-elastic-containers.sh" 


    # Setup the Elastic Stack
    cfg.vm.provision "shell" do |s2|
      s2.path = "../vagrant/scripts/elastic/setup-elastic.sh"
      s2.env = {
        "ELASTIC_STACK_VERSION" => "8.15.3",
        "KIBANA_URL" => "https://192.168.56.10:5601",
        "KIBANA_AUTH" => "elastic:vagrant",
        "ELASTICSEARCH_URL" => "https://192.168.56.10:9200",
        "FLEET_SERVER_URL" => "https://192.168.56.10:8220"
      }
    end

    # Install Vectr
    if ENV['VECTR_INSTALL'] == "true"    
      cfg.vm.network "forwarded_port", guest: 8081, host: 8081
      cfg.vm.provision "install-vectr", type: "shell", path: "../vagrant/scripts/elastic/install-vectr.sh"
    end


    # Install Velociraptor Server
    if ENV['velociraptor_install'] == "true"
      cfg.vm.network "forwarded_port", guest: 8889, host: 9000
      #cfg.vm.provision "transfer-velox-msi", type: "file", source: "../vagrant/resources/velox/clients/windows/velociraptor_client_repacked.msi", destination: "C:\\tmp\\velociraptor_client_repacked.msi"
      cfg.vm.provision "install-velociraptor-server", type: "shell", path: "../vagrant/scripts/elastic/install-velociraptor-server.sh"
    end
  end
  

  config.vm.define "ts.windows10" do |cfg|
    cfg.vm.box = "olympus/windows10"
    cfg.vm.box_version = "1.0.1"
    cfg.vm.hostname = "windows10"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.56.11", gateway: "192.168.56.1", dns: "192.168.56.14"
    config.vm.network "forwarded_port", guest: 3389, host: 33389, auto_correct: true
    config.vm.network "forwarded_port", guest: 5985, host: 55985, auto_correct: true


    
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "ts.windows10"
      vb.memory = 2048
      vb.cpus = 2
    end
    cfg.vm.provision "exprfix", type: "shell", path: "../vagrant/scripts/windows10/fix-windows-expiration.ps1"
    cfg.vm.provision "install-chocolatey", type: "shell", path: "../vagrant/scripts/install-choco.ps1"
    cfg.vm.provision "install-pwshssh", type: "shell", path: "../vagrant/scripts/windows10/install-pwshssh.ps1"
    cfg.vm.provision "install-sysmon", type: "shell", path: "../vagrant/scripts/windows10/install-sysmon.ps1"
    cfg.vm.provision "install-advaudit", type: "shell", path: "../vagrant/scripts/windows10/install-advaudit.ps1"

    if ENV['DC'] == "ts.dc"
      cfg.vm.provision "join-domain", type: "shell", path: "../vagrant/scripts/join-domain.ps1"
      cfg.vm.provision "reload"
    end
    
    # Install Pneuma Agent
    if ENV['operator_install'] == "true" 
      cfg.vm.provision "download-install-pneuma-windows", type: "shell", path: "../vagrant/scripts/windows10/download-pneuma-windows.ps1"
    end

    # Install Nextron Aurora Agent
    if ENV['aurora_install'] == "true"
      cfg.vm.provision "file", source: "resources/aurora/aurora-lite.lic", destination: "C:/aurora-agent/aurora-lite.lic"
      cfg.vm.provision "install-aurora-agent", type: "shell", path: "../vagrant/scripts/windows10/install-aurora.ps1"
    end

    # Install Hayabusa
    if ENV['hayabusa_install'] == "true"
      cfg.vm.provision "install-hayabusa", type: "shell", path: "../vagrant/scripts/windows10/install-hayabusa.ps1"
    end

    # Install Velociraptor Client
    if ENV['velociraptor_install'] == "true"
      cfg.vm.provision "install_velociraptor", type: "shell", path: "../vagrant/scripts/windows10/install-velox-client-windows.ps1"
    end

    #cfg.vm.provision "shutup10", type: "shell", path: "../vagrant/scripts/install-shutup10config.ps1"
    cfg.vm.provision "shell" do |s|
      s.path = "../vagrant/scripts/windows10/install-ea.ps1"
      s.env = {
        "ELASTIC_STACK_VERSION" => '8.15.3',
        "KIBANA_URL" => 'https://192.168.56.10:5601',
        "KIBANA_AUTH" => 'elastic:vagrant',
        "ELASTICSEARCH_URL" => 'https://192.168.56.10:9200',
        "FLEET_SERVER_URL" => 'https://192.168.56.10:8220'
      }
    end
  end



  config.vm.define "ts.rocky9" do |cfg|
    cfg.vm.box = "bento/rockylinux-9"
    cfg.vm.box_version = "202401.31.0 "
    cfg.vm.hostname = "rocky9"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.56.12", auto_config: true
    cfg.vm.network "forwarded_port", guest: 80, host: 8080
    cfg.vm.network "forwarded_port", guest: 9090, host: 9090
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "ts.rocky9"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    # Enable PowerShell Remoting
    cfg.vm.provision "enable-psremoting", type: "shell", path: "../vagrant/scripts/enable-psremoting.sh"

    # Setup Samba/Nginx
    cfg.vm.provision "setup-services", type: "shell", path: "../vagrant/scripts/rocky9/setup-client-services.sh"


    # Install SigmaCLI and Rules
    if ENV['sigma_install'] == "true"
      cfg.vm.provision "install_sigma", type: "shell", path: "../vagrant/scripts/rocky9/install-sigma.sh"
    end
    
    # Install Prelude Operator
    if ENV['operator_install'] == "true" 
      cfg.vm.provision "download-install-pneuma-linux", type: "shell", path: "../vagrant/scripts/rocky9/download-pneuma-linux.sh"
    end

    # Install Velociraptor Client
    if ENV['velociraptor_install'] == "true"
      cfg.vm.provision "install_velociraptor", type: "shell", path: "../vagrant/scripts/rocky9/install-velox-client-linux.sh"
    end


    # Install and Enroll Elastic Agent
    cfg.vm.provision "shell" do |s|
      s.path = "../vagrant/scripts/rocky9/install-ea-linux.sh"
      s.env = {
        "ELASTIC_STACK_VERSION" => "8.15.3",
        "KIBANA_URL" => "https://192.168.56.10:5601",
        "KIBANA_AUTH" => "elastic:vagrant",
        "ELASTICSEARCH_URL" => "https://192.168.56.10:9200",
        "FLEET_SERVER_URL" => "https://192.168.56.10:8220"
      }
    end
  end

  config.vm.define "ts.redops" do |cfg|
    cfg.vm.box = "kalilinux/rolling"
    cfg.vm.box_version = "2024.1.0"
    cfg.vm.hostname = "kali"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.56.13", auto_config: true
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "ts.redops"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      end
  end

  config.vm.define "ts.dc" do |cfg|
    cfg.vm.box = "gusztavvargadr/windows-server-2019-standard-core"
    cfg.vm.box_version = "1809.0.2402"
    cfg.vm.hostname = "dc"
    cfg.winrm.transport = :plaintext
    cfg.winrm.basic_auth_only = true
    cfg.vm.network "private_network", ip: "192.168.56.14", gateway: "192.168.56.1", dns: "8.8.8.8"
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "ts.dc"
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    # Create Thremulator Domain
    cfg.vm.provision "create-domain", type: "shell", path: "../vagrant/scripts/dc/create-domain.ps1", args: "192.168.56.14"
    
    # Restart DC
    cfg.vm.provision :reload

    # Configure OU
    cfg.vm.provision "configure-ou", type: "shell", path: "../vagrant/scripts/dc/configure-ou.ps1"
    
    # Install Chocolatey
    cfg.vm.provision "install-chocolatey", type: "shell", path: "../vagrant/scripts/install-choco.ps1"
    
    # Install Badblood
    cfg.vm.provision "install-badblood", type: "shell", path: "../vagrant/scripts/dc/install-badblood.ps1"

    # Install Velociraptor Client
    if ENV['velociraptor_install'] == "true"
      cfg.vm.provision "install_velociraptor", type: "shell", path: "../vagrant/scripts/windows10/install-velox-client-windows.ps1"
    end

    # Install Elastic Agent
    cfg.vm.provision "shell" do |s|
      s.path = "../vagrant/scripts/windows10/install-ea.ps1"
      s.env = {
        "ELASTIC_STACK_VERSION" => '8.15.3',
        "KIBANA_URL" => 'https://192.168.56.10:5601',
        "KIBANA_AUTH" => 'elastic:vagrant',
        "ELASTICSEARCH_URL" => 'https://192.168.56.10:9200',
        "FLEET_SERVER_URL" => 'https://192.168.56.10:8220'
      }
    end
  end
end